### ISSUE TITLE
打开UIPage后，找不到办法在UI脚本内获取该UIPage的IUIEntity

### ISSUE THREAD

**Issue by Cardidi** [yomunsam/TinaX.UIKit#4]
我在尝试写一个对话UI的脚本，并且这个脚本是这个UIPage的UI处理者。

我希望在对话结束之后，在该脚本内让这个UIPage关闭。但是我发觉，似乎只能通过`UIKit.CloseUI("targetUIPageName")`的方法关闭。我觉得这个办法有一点不安全，如果不小心动了UIGroup的配置，可能就不会生效了。

所以我想问一下有没有什么办法能够直接获取这个UIPage的IUIEntity，以直接对这个UI进行操作，而不是通过我刚刚提到的办法进行操作？

**Comment by yomunsam** [comment]
脚本继承自 `XUIBehaviour`的话，可以直接`this.Close();`

目前Examples更新后也用这个写法了

详见：https://github.com/yomunsam/TinaX.UIKit/blob/master/Runtime/Scripts/XUIBehaviour.cs
